#!/bin/sh

BASE=$(cd `dirname $0`/.. && pwd)

DAEMONIZE=/usr/sbin/daemonize
test ! -f $DAEMONIZE && DAEMONIZE=/usr/local/sbin/daemonize

NODEJS=`which node`
test ! -f $NODEJS && NODEJS=~naitik/.nave/installed/latest/bin/node

$DAEMONIZE $NODEJS $BASE/server.js
