#!/bin/sh

BASE=$(cd `dirname $0`/.. && pwd)

DAEMONIZE=/usr/sbin/daemonize
test ! -f $DAEMONIZE && DAEMONIZE=/usr/local/sbin/daemonize

NODE=`which node`
test ! -f $NODE && NODE=~naitik/.nave/installed/latest/bin/node

$DAEMONIZE \
  -o /data/log/fbrell.out \
  -e /data/log/fbrell.err \
  $NODE $BASE/app.js
