#!/bin/sh

/usr/sbin/daemonize \
  -a \
  -e /data/log/fbrell.node.err \
  -o /data/log/fbrell.node.out \
  /home/naitik/.nave/installed/latest/bin/node \
  /home/naitik/.nave/installed/latest/bin/spark \
  --env production \
  --chdir /data/www/fbrell \
  --comment fbrell_server \
  --port 43600
