#!/bin/sh

set -e

bump_pkgver() {
  new_version=$(git log --pretty=format:'' | wc -l)
  sed -i -e "s/pkgver=.*/pkgver=$new_version/" PKGBUILD
}

pkgname() {
  grep "pkgname=" PKGBUILD | sed -e 's/pkgname=//'
}

REV=$1
DIR=$(cd $(dirname "$0"); pwd)
cd $DIR/$REV
PKGNAME=$(pkgname)
echo "Pushing $REV ($PKGNAME)"
bump_pkgver
makepkg --holdver
mkdir -p ~/pkgs/repo
PKGS=$(ls *pkg.tar.xz)
mv $PKGS ~/pkgs/repo/
repo-add ~/pkgs/repo/custom-x86_64.db.tar.gz ~/pkgs/repo/$PKGS
ssh daaku "echo y | pacman -Sy $PKGNAME etc-conf-$PKGNAME && systemctl --system daemon-reload && systemctl stop $PKGNAME.service"
