#!/bin/sh

set -e

bump_pkgver() {
  current_full=$(cat PKGBUILD | grep pkgver)
  new_version=$(echo $current_full | sed -e 's/.*=//' | awk '{print $1 + 1}')
  sed -i -e "s/$current_full/pkgver=$new_version/" PKGBUILD
}

REV=$1
DIR=$(cd $(dirname "$0"); pwd)
echo "Pushing $REV"
cd $DIR/$REV
bump_pkgver
makepkg --holdver
mkdir -p ~/pkgs/repo
PKGS=$(ls *pkg.tar.xz)
mv $PKGS ~/pkgs/repo/
repo-add ~/pkgs/repo/custom.db.tar.gz ~/pkgs/repo/$PKGS
echo "y" | sudo pacman -Sy rell-$REV
sudo /etc/rc.d/rell-$REV restart
