#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PKGNAME=`basename $0`
DAEMON_COMMAND=/usr/bin/$PKGNAME
DAEMON_OUT=/var/log/$PKGNAME.out
DAEMON_ERR=/var/log/$PKGNAME.err
DAEMON_PID=/run/$PKGNAME.pid
DAEMON_PID=/run/lock/$PKGNAME.lock
CONF_FILE=/etc/conf.d/$PKGNAME
PID=$(pidof -o %PPID $DAEMON_COMMAND)

case $1 in
start)
	stat_busy "Starting $PKGNAME Daemon"

  if [[ ! -z $PID ]]; then
		stat_fail
		exit 1
  fi

  touch $DAEMON_OUT
  touch $DAEMON_ERR
  chown $PKGNAME:$PKGNAME $DAEMON_OUT
  chown $PKGNAME:$PKGNAME $DAEMON_ERR

  daemonize \
    -a \
    -c / \
    -e $DAEMON_ERR \
    -o $DAEMON_OUT \
    -u $PKGNAME \
    -p $DAEMON_PID \
    -l $DAEMON_PID \
    \
    $DAEMON_COMMAND -c $CONF_FILE
  if [[ $? -ne 0 ]]; then
		stat_fail
		exit 1
  fi
	add_daemon $PKGNAME
	stat_done
	;;

stop)
	stat_busy "Stopping $PKGNAME Daemon"
	if [[ ! -z $PID ]]  && kill "$PID" &>/dev/null; then
		rm_daemon $PKGNAME
		stat_done
	else
		stat_fail
		exit 1
	fi
	;;

restart)
	$0 stop
	$0 start
	;;

*)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1

esac
